#!/bin/bash

usage() {
	echo --------------------------------------------------
	echo "usage: $0 <absolute-install-path>"
	echo --------------------------------------------------
}

if [ $# -lt 1 ]; then
	usage
	exit
fi

prefix=$1
echo "AVXSYNTH_LIB_INSTALL_PATH = "$prefix > common.mk
cat common.mk.template >> common.mk
